// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: configuration.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getConfiguration = `-- name: GetConfiguration :one
select id, nutrition_calories_target, nutrition_protein_target, nutrition_carbs_target, nutrition_fat_target, created_at from configuration
limit 1
`

func (q *Queries) GetConfiguration(ctx context.Context) (Configuration, error) {
	row := q.db.QueryRow(ctx, getConfiguration)
	var i Configuration
	err := row.Scan(
		&i.ID,
		&i.NutritionCaloriesTarget,
		&i.NutritionProteinTarget,
		&i.NutritionCarbsTarget,
		&i.NutritionFatTarget,
		&i.CreatedAt,
	)
	return i, err
}

const updateConfiguration = `-- name: UpdateConfiguration :one
update configuration
set nutrition_calories_target = $1,
    nutrition_protein_target = $2,
    nutrition_carbs_target = $3,
    nutrition_fat_target = $4
returning id, nutrition_calories_target, nutrition_protein_target, nutrition_carbs_target, nutrition_fat_target, created_at
`

type UpdateConfigurationParams struct {
	NutritionCaloriesTarget pgtype.Numeric `json:"nutrition_calories_target"`
	NutritionProteinTarget  pgtype.Numeric `json:"nutrition_protein_target"`
	NutritionCarbsTarget    pgtype.Numeric `json:"nutrition_carbs_target"`
	NutritionFatTarget      pgtype.Numeric `json:"nutrition_fat_target"`
}

func (q *Queries) UpdateConfiguration(ctx context.Context, arg UpdateConfigurationParams) (Configuration, error) {
	row := q.db.QueryRow(ctx, updateConfiguration,
		arg.NutritionCaloriesTarget,
		arg.NutritionProteinTarget,
		arg.NutritionCarbsTarget,
		arg.NutritionFatTarget,
	)
	var i Configuration
	err := row.Scan(
		&i.ID,
		&i.NutritionCaloriesTarget,
		&i.NutritionProteinTarget,
		&i.NutritionCarbsTarget,
		&i.NutritionFatTarget,
		&i.CreatedAt,
	)
	return i, err
}
