// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: foods.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createFood = `-- name: CreateFood :one
insert into foods (
  name, serving_label, calories_per_serving, protein_per_serving, carbs_per_serving, fat_per_serving
)
values ($1, $2, $3, $4, $5, $6)
returning id, name, serving_label, calories_per_serving, protein_per_serving, carbs_per_serving, fat_per_serving, created_at
`

type CreateFoodParams struct {
	Name               string         `json:"name"`
	ServingLabel       string         `json:"serving_label"`
	CaloriesPerServing pgtype.Numeric `json:"calories_per_serving"`
	ProteinPerServing  pgtype.Numeric `json:"protein_per_serving"`
	CarbsPerServing    pgtype.Numeric `json:"carbs_per_serving"`
	FatPerServing      pgtype.Numeric `json:"fat_per_serving"`
}

func (q *Queries) CreateFood(ctx context.Context, arg CreateFoodParams) (Food, error) {
	row := q.db.QueryRow(ctx, createFood,
		arg.Name,
		arg.ServingLabel,
		arg.CaloriesPerServing,
		arg.ProteinPerServing,
		arg.CarbsPerServing,
		arg.FatPerServing,
	)
	var i Food
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ServingLabel,
		&i.CaloriesPerServing,
		&i.ProteinPerServing,
		&i.CarbsPerServing,
		&i.FatPerServing,
		&i.CreatedAt,
	)
	return i, err
}

const createFoodEntry = `-- name: CreateFoodEntry :one
insert into food_entries (food_id, name, quantity, calories, protein, carbs, fat, date, meal_slot)
values ($1, $2, $3, $4, $5, $6, $7, $8, $9)
returning id, food_id, name, quantity, calories, protein, carbs, fat, date, created_at, meal_slot
`

type CreateFoodEntryParams struct {
	FoodID   pgtype.UUID    `json:"food_id"`
	Name     string         `json:"name"`
	Quantity pgtype.Numeric `json:"quantity"`
	Calories pgtype.Numeric `json:"calories"`
	Protein  pgtype.Numeric `json:"protein"`
	Carbs    pgtype.Numeric `json:"carbs"`
	Fat      pgtype.Numeric `json:"fat"`
	Date     pgtype.Date    `json:"date"`
	MealSlot string         `json:"meal_slot"`
}

func (q *Queries) CreateFoodEntry(ctx context.Context, arg CreateFoodEntryParams) (FoodEntry, error) {
	row := q.db.QueryRow(ctx, createFoodEntry,
		arg.FoodID,
		arg.Name,
		arg.Quantity,
		arg.Calories,
		arg.Protein,
		arg.Carbs,
		arg.Fat,
		arg.Date,
		arg.MealSlot,
	)
	var i FoodEntry
	err := row.Scan(
		&i.ID,
		&i.FoodID,
		&i.Name,
		&i.Quantity,
		&i.Calories,
		&i.Protein,
		&i.Carbs,
		&i.Fat,
		&i.Date,
		&i.CreatedAt,
		&i.MealSlot,
	)
	return i, err
}

const deleteFood = `-- name: DeleteFood :exec
delete from foods
where id = $1
`

func (q *Queries) DeleteFood(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteFood, id)
	return err
}

const deleteFoodEntry = `-- name: DeleteFoodEntry :exec
delete from food_entries
where id = $1
`

func (q *Queries) DeleteFoodEntry(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteFoodEntry, id)
	return err
}

const getFood = `-- name: GetFood :one
select id, name, serving_label, calories_per_serving, protein_per_serving, carbs_per_serving, fat_per_serving, created_at from foods
where id = $1
`

func (q *Queries) GetFood(ctx context.Context, id pgtype.UUID) (Food, error) {
	row := q.db.QueryRow(ctx, getFood, id)
	var i Food
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ServingLabel,
		&i.CaloriesPerServing,
		&i.ProteinPerServing,
		&i.CarbsPerServing,
		&i.FatPerServing,
		&i.CreatedAt,
	)
	return i, err
}

const getFoodEntry = `-- name: GetFoodEntry :one
select id, food_id, name, quantity, calories, protein, carbs, fat, date, created_at, meal_slot from food_entries
where id = $1
`

func (q *Queries) GetFoodEntry(ctx context.Context, id pgtype.UUID) (FoodEntry, error) {
	row := q.db.QueryRow(ctx, getFoodEntry, id)
	var i FoodEntry
	err := row.Scan(
		&i.ID,
		&i.FoodID,
		&i.Name,
		&i.Quantity,
		&i.Calories,
		&i.Protein,
		&i.Carbs,
		&i.Fat,
		&i.Date,
		&i.CreatedAt,
		&i.MealSlot,
	)
	return i, err
}

const listFoodEntries = `-- name: ListFoodEntries :many
select id, food_id, name, quantity, calories, protein, carbs, fat, date, created_at, meal_slot from food_entries
order by date desc, created_at desc
`

func (q *Queries) ListFoodEntries(ctx context.Context) ([]FoodEntry, error) {
	rows, err := q.db.Query(ctx, listFoodEntries)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FoodEntry
	for rows.Next() {
		var i FoodEntry
		if err := rows.Scan(
			&i.ID,
			&i.FoodID,
			&i.Name,
			&i.Quantity,
			&i.Calories,
			&i.Protein,
			&i.Carbs,
			&i.Fat,
			&i.Date,
			&i.CreatedAt,
			&i.MealSlot,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFoods = `-- name: ListFoods :many
select id, name, serving_label, calories_per_serving, protein_per_serving, carbs_per_serving, fat_per_serving, created_at from foods
order by name asc
`

func (q *Queries) ListFoods(ctx context.Context) ([]Food, error) {
	rows, err := q.db.Query(ctx, listFoods)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Food
	for rows.Next() {
		var i Food
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ServingLabel,
			&i.CaloriesPerServing,
			&i.ProteinPerServing,
			&i.CarbsPerServing,
			&i.FatPerServing,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateFood = `-- name: UpdateFood :one
update foods
set
  name = coalesce($2, name),
  serving_label = coalesce($3, serving_label),
  calories_per_serving = coalesce($4, calories_per_serving),
  protein_per_serving = coalesce($5, protein_per_serving),
  carbs_per_serving = coalesce($6, carbs_per_serving),
  fat_per_serving = coalesce($7, fat_per_serving)
where id = $1
returning id, name, serving_label, calories_per_serving, protein_per_serving, carbs_per_serving, fat_per_serving, created_at
`

type UpdateFoodParams struct {
	ID                 pgtype.UUID    `json:"id"`
	Name               pgtype.Text    `json:"name"`
	ServingLabel       pgtype.Text    `json:"serving_label"`
	CaloriesPerServing pgtype.Numeric `json:"calories_per_serving"`
	ProteinPerServing  pgtype.Numeric `json:"protein_per_serving"`
	CarbsPerServing    pgtype.Numeric `json:"carbs_per_serving"`
	FatPerServing      pgtype.Numeric `json:"fat_per_serving"`
}

func (q *Queries) UpdateFood(ctx context.Context, arg UpdateFoodParams) (Food, error) {
	row := q.db.QueryRow(ctx, updateFood,
		arg.ID,
		arg.Name,
		arg.ServingLabel,
		arg.CaloriesPerServing,
		arg.ProteinPerServing,
		arg.CarbsPerServing,
		arg.FatPerServing,
	)
	var i Food
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ServingLabel,
		&i.CaloriesPerServing,
		&i.ProteinPerServing,
		&i.CarbsPerServing,
		&i.FatPerServing,
		&i.CreatedAt,
	)
	return i, err
}

const updateFoodEntryQuantity = `-- name: UpdateFoodEntryQuantity :one
update food_entries
set quantity = $2, calories = $3, protein = $4, carbs = $5, fat = $6, meal_slot = $7
where id = $1
returning id, food_id, name, quantity, calories, protein, carbs, fat, date, created_at, meal_slot
`

type UpdateFoodEntryQuantityParams struct {
	ID       pgtype.UUID    `json:"id"`
	Quantity pgtype.Numeric `json:"quantity"`
	Calories pgtype.Numeric `json:"calories"`
	Protein  pgtype.Numeric `json:"protein"`
	Carbs    pgtype.Numeric `json:"carbs"`
	Fat      pgtype.Numeric `json:"fat"`
	MealSlot string         `json:"meal_slot"`
}

func (q *Queries) UpdateFoodEntryQuantity(ctx context.Context, arg UpdateFoodEntryQuantityParams) (FoodEntry, error) {
	row := q.db.QueryRow(ctx, updateFoodEntryQuantity,
		arg.ID,
		arg.Quantity,
		arg.Calories,
		arg.Protein,
		arg.Carbs,
		arg.Fat,
		arg.MealSlot,
	)
	var i FoodEntry
	err := row.Scan(
		&i.ID,
		&i.FoodID,
		&i.Name,
		&i.Quantity,
		&i.Calories,
		&i.Protein,
		&i.Carbs,
		&i.Fat,
		&i.Date,
		&i.CreatedAt,
		&i.MealSlot,
	)
	return i, err
}
