// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: habits.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countActiveHabits = `-- name: CountActiveHabits :one
select count(*) from habits
where active = true
`

func (q *Queries) CountActiveHabits(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveHabits)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createHabit = `-- name: CreateHabit :one
insert into habits (name, active, position)
values ($1, true, (select coalesce(max(position), -1) + 1 from habits))
returning id, name, active, position, created_at
`

func (q *Queries) CreateHabit(ctx context.Context, name string) (Habit, error) {
	row := q.db.QueryRow(ctx, createHabit, name)
	var i Habit
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Active,
		&i.Position,
		&i.CreatedAt,
	)
	return i, err
}

const createHabitEntry = `-- name: CreateHabitEntry :one
insert into habit_entries (habit_id, date)
values ($1, $2)
returning id, habit_id, date, created_at
`

type CreateHabitEntryParams struct {
	HabitID pgtype.UUID `json:"habit_id"`
	Date    pgtype.Date `json:"date"`
}

func (q *Queries) CreateHabitEntry(ctx context.Context, arg CreateHabitEntryParams) (HabitEntry, error) {
	row := q.db.QueryRow(ctx, createHabitEntry, arg.HabitID, arg.Date)
	var i HabitEntry
	err := row.Scan(
		&i.ID,
		&i.HabitID,
		&i.Date,
		&i.CreatedAt,
	)
	return i, err
}

const deleteHabitEntry = `-- name: DeleteHabitEntry :exec
delete from habit_entries
where id = $1
`

func (q *Queries) DeleteHabitEntry(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteHabitEntry, id)
	return err
}

const getHabit = `-- name: GetHabit :one
select id, name, active, position, created_at from habits
where id = $1
`

func (q *Queries) GetHabit(ctx context.Context, id pgtype.UUID) (Habit, error) {
	row := q.db.QueryRow(ctx, getHabit, id)
	var i Habit
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Active,
		&i.Position,
		&i.CreatedAt,
	)
	return i, err
}

const listHabitEntries = `-- name: ListHabitEntries :many
select id, habit_id, date, created_at from habit_entries
order by date desc, created_at desc
`

func (q *Queries) ListHabitEntries(ctx context.Context) ([]HabitEntry, error) {
	rows, err := q.db.Query(ctx, listHabitEntries)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []HabitEntry
	for rows.Next() {
		var i HabitEntry
		if err := rows.Scan(
			&i.ID,
			&i.HabitID,
			&i.Date,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHabits = `-- name: ListHabits :many
select id, name, active, position, created_at from habits
order by position asc
`

func (q *Queries) ListHabits(ctx context.Context) ([]Habit, error) {
	rows, err := q.db.Query(ctx, listHabits)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Habit
	for rows.Next() {
		var i Habit
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Active,
			&i.Position,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reorderHabits = `-- name: ReorderHabits :exec
update habits
set position = t.idx - 1
from unnest($1::uuid[]) with ordinality as t(id, idx)
where habits.id = t.id
`

func (q *Queries) ReorderHabits(ctx context.Context, ids []pgtype.UUID) error {
	_, err := q.db.Exec(ctx, reorderHabits, ids)
	return err
}

const updateHabit = `-- name: UpdateHabit :one
update habits
set
  name = coalesce($2, name),
  active = coalesce($3, active)
where id = $1
returning id, name, active, position, created_at
`

type UpdateHabitParams struct {
	ID     pgtype.UUID `json:"id"`
	Name   pgtype.Text `json:"name"`
	Active pgtype.Bool `json:"active"`
}

func (q *Queries) UpdateHabit(ctx context.Context, arg UpdateHabitParams) (Habit, error) {
	row := q.db.QueryRow(ctx, updateHabit, arg.ID, arg.Name, arg.Active)
	var i Habit
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Active,
		&i.Position,
		&i.CreatedAt,
	)
	return i, err
}
