// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: measurements.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createMeasurement = `-- name: CreateMeasurement :one
insert into measurements (date, kg)
values ($1, $2)
returning id, date, kg, created_at
`

type CreateMeasurementParams struct {
	Date pgtype.Date    `json:"date"`
	Kg   pgtype.Numeric `json:"kg"`
}

func (q *Queries) CreateMeasurement(ctx context.Context, arg CreateMeasurementParams) (Measurement, error) {
	row := q.db.QueryRow(ctx, createMeasurement, arg.Date, arg.Kg)
	var i Measurement
	err := row.Scan(
		&i.ID,
		&i.Date,
		&i.Kg,
		&i.CreatedAt,
	)
	return i, err
}

const deleteMeasurement = `-- name: DeleteMeasurement :exec
delete from measurements
where id = $1
`

func (q *Queries) DeleteMeasurement(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteMeasurement, id)
	return err
}

const listMeasurements = `-- name: ListMeasurements :many
select id, date, kg, created_at from measurements
order by date desc, created_at desc
`

func (q *Queries) ListMeasurements(ctx context.Context) ([]Measurement, error) {
	rows, err := q.db.Query(ctx, listMeasurements)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Measurement
	for rows.Next() {
		var i Measurement
		if err := rows.Scan(
			&i.ID,
			&i.Date,
			&i.Kg,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMeasurement = `-- name: UpdateMeasurement :one
update measurements
set date = $2, kg = $3
where id = $1
returning id, date, kg, created_at
`

type UpdateMeasurementParams struct {
	ID   pgtype.UUID    `json:"id"`
	Date pgtype.Date    `json:"date"`
	Kg   pgtype.Numeric `json:"kg"`
}

func (q *Queries) UpdateMeasurement(ctx context.Context, arg UpdateMeasurementParams) (Measurement, error) {
	row := q.db.QueryRow(ctx, updateMeasurement, arg.ID, arg.Date, arg.Kg)
	var i Measurement
	err := row.Scan(
		&i.ID,
		&i.Date,
		&i.Kg,
		&i.CreatedAt,
	)
	return i, err
}
