// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package database

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type TokenScope string

const (
	TokenScopeReadOnly  TokenScope = "read_only"
	TokenScopeReadWrite TokenScope = "read_write"
)

func (e *TokenScope) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TokenScope(s)
	case string:
		*e = TokenScope(s)
	default:
		return fmt.Errorf("unsupported scan type for TokenScope: %T", src)
	}
	return nil
}

type NullTokenScope struct {
	TokenScope TokenScope `json:"token_scope"`
	Valid      bool       `json:"valid"` // Valid is true if TokenScope is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTokenScope) Scan(value interface{}) error {
	if value == nil {
		ns.TokenScope, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TokenScope.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTokenScope) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TokenScope), nil
}

type Configuration struct {
	ID                      pgtype.UUID        `json:"id"`
	NutritionCaloriesTarget pgtype.Numeric     `json:"nutrition_calories_target"`
	NutritionProteinTarget  pgtype.Numeric     `json:"nutrition_protein_target"`
	NutritionCarbsTarget    pgtype.Numeric     `json:"nutrition_carbs_target"`
	NutritionFatTarget      pgtype.Numeric     `json:"nutrition_fat_target"`
	CreatedAt               pgtype.Timestamptz `json:"created_at"`
}

type Exercise struct {
	ID          pgtype.UUID        `json:"id"`
	Name        string             `json:"name"`
	Type        string             `json:"type"`
	WorkoutType string             `json:"workout_type"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type Food struct {
	ID                 pgtype.UUID        `json:"id"`
	Name               string             `json:"name"`
	ServingLabel       string             `json:"serving_label"`
	CaloriesPerServing pgtype.Numeric     `json:"calories_per_serving"`
	ProteinPerServing  pgtype.Numeric     `json:"protein_per_serving"`
	CarbsPerServing    pgtype.Numeric     `json:"carbs_per_serving"`
	FatPerServing      pgtype.Numeric     `json:"fat_per_serving"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
}

type FoodEntry struct {
	ID        pgtype.UUID        `json:"id"`
	FoodID    pgtype.UUID        `json:"food_id"`
	Name      string             `json:"name"`
	Quantity  pgtype.Numeric     `json:"quantity"`
	Calories  pgtype.Numeric     `json:"calories"`
	Protein   pgtype.Numeric     `json:"protein"`
	Carbs     pgtype.Numeric     `json:"carbs"`
	Fat       pgtype.Numeric     `json:"fat"`
	Date      pgtype.Date        `json:"date"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	MealSlot  string             `json:"meal_slot"`
}

type Habit struct {
	ID        pgtype.UUID        `json:"id"`
	Name      string             `json:"name"`
	Active    bool               `json:"active"`
	Position  int32              `json:"position"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type HabitEntry struct {
	ID        pgtype.UUID        `json:"id"`
	HabitID   pgtype.UUID        `json:"habit_id"`
	Date      pgtype.Date        `json:"date"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Measurement struct {
	ID        pgtype.UUID        `json:"id"`
	Date      pgtype.Date        `json:"date"`
	Kg        pgtype.Numeric     `json:"kg"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Token struct {
	ID        pgtype.UUID        `json:"id"`
	TokenHash string             `json:"token_hash"`
	Label     string             `json:"label"`
	Scope     TokenScope         `json:"scope"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	RevokedAt pgtype.Timestamptz `json:"revoked_at"`
}

type WorkoutSession struct {
	ID          pgtype.UUID        `json:"id"`
	WorkoutType string             `json:"workout_type"`
	TemplateID  pgtype.UUID        `json:"template_id"`
	Note        pgtype.Text        `json:"note"`
	Date        pgtype.Date        `json:"date"`
	FinishedAt  pgtype.Timestamptz `json:"finished_at"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type WorkoutSessionExercise struct {
	ID           pgtype.UUID        `json:"id"`
	SessionID    pgtype.UUID        `json:"session_id"`
	ExerciseID   pgtype.UUID        `json:"exercise_id"`
	ExerciseName string             `json:"exercise_name"`
	Note         pgtype.Text        `json:"note"`
	Position     int32              `json:"position"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type WorkoutSet struct {
	ID                pgtype.UUID        `json:"id"`
	SessionExerciseID pgtype.UUID        `json:"session_exercise_id"`
	SetType           string             `json:"set_type"`
	Confirmed         bool               `json:"confirmed"`
	Note              pgtype.Text        `json:"note"`
	WeightKg          pgtype.Numeric     `json:"weight_kg"`
	Reps              pgtype.Int4        `json:"reps"`
	DurationSec       pgtype.Int4        `json:"duration_sec"`
	DistanceM         pgtype.Numeric     `json:"distance_m"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
}

type WorkoutTemplate struct {
	ID          pgtype.UUID        `json:"id"`
	Name        string             `json:"name"`
	WorkoutType string             `json:"workout_type"`
	IsDefault   bool               `json:"is_default"`
	Archived    bool               `json:"archived"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type WorkoutTemplateSet struct {
	ID           pgtype.UUID        `json:"id"`
	TemplateID   pgtype.UUID        `json:"template_id"`
	ExerciseID   pgtype.UUID        `json:"exercise_id"`
	ExerciseName string             `json:"exercise_name"`
	Position     int32              `json:"position"`
	SetType      string             `json:"set_type"`
	WeightKg     pgtype.Numeric     `json:"weight_kg"`
	Reps         pgtype.Int4        `json:"reps"`
	DurationSec  pgtype.Int4        `json:"duration_sec"`
	DistanceM    pgtype.Numeric     `json:"distance_m"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}
