// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package database

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Measurement struct {
	ID        pgtype.UUID        `json:"id"`
	Date      pgtype.Date        `json:"date"`
	Kg        pgtype.Numeric     `json:"kg"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}
