// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package database

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type TokenScope string

const (
	TokenScopeReadOnly  TokenScope = "read_only"
	TokenScopeReadWrite TokenScope = "read_write"
)

func (e *TokenScope) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TokenScope(s)
	case string:
		*e = TokenScope(s)
	default:
		return fmt.Errorf("unsupported scan type for TokenScope: %T", src)
	}
	return nil
}

type NullTokenScope struct {
	TokenScope TokenScope `json:"token_scope"`
	Valid      bool       `json:"valid"` // Valid is true if TokenScope is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTokenScope) Scan(value interface{}) error {
	if value == nil {
		ns.TokenScope, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TokenScope.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTokenScope) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TokenScope), nil
}

type Food struct {
	ID                 pgtype.UUID        `json:"id"`
	Name               string             `json:"name"`
	ServingLabel       string             `json:"serving_label"`
	CaloriesPerServing pgtype.Numeric     `json:"calories_per_serving"`
	ProteinPerServing  pgtype.Numeric     `json:"protein_per_serving"`
	CarbsPerServing    pgtype.Numeric     `json:"carbs_per_serving"`
	FatPerServing      pgtype.Numeric     `json:"fat_per_serving"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
}

type FoodEntry struct {
	ID        pgtype.UUID        `json:"id"`
	FoodID    pgtype.UUID        `json:"food_id"`
	Name      string             `json:"name"`
	Quantity  pgtype.Numeric     `json:"quantity"`
	Calories  pgtype.Numeric     `json:"calories"`
	Protein   pgtype.Numeric     `json:"protein"`
	Carbs     pgtype.Numeric     `json:"carbs"`
	Fat       pgtype.Numeric     `json:"fat"`
	Date      pgtype.Date        `json:"date"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Habit struct {
	ID        pgtype.UUID        `json:"id"`
	Name      string             `json:"name"`
	Active    bool               `json:"active"`
	Position  int32              `json:"position"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type HabitEntry struct {
	ID        pgtype.UUID        `json:"id"`
	HabitID   pgtype.UUID        `json:"habit_id"`
	Date      pgtype.Date        `json:"date"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Measurement struct {
	ID        pgtype.UUID        `json:"id"`
	Date      pgtype.Date        `json:"date"`
	Kg        pgtype.Numeric     `json:"kg"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Token struct {
	ID        pgtype.UUID        `json:"id"`
	TokenHash string             `json:"token_hash"`
	Label     string             `json:"label"`
	Scope     TokenScope         `json:"scope"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	RevokedAt pgtype.Timestamptz `json:"revoked_at"`
}
