// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateMeasurement(ctx context.Context, arg CreateMeasurementParams) (Measurement, error)
	DeleteMeasurement(ctx context.Context, id pgtype.UUID) error
	ListMeasurements(ctx context.Context) ([]Measurement, error)
	UpdateMeasurement(ctx context.Context, arg UpdateMeasurementParams) (Measurement, error)
}

var _ Querier = (*Queries)(nil)
