// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tokens.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createToken = `-- name: CreateToken :one
insert into tokens (token_hash, label, scope)
values ($1, $2, $3)
returning id, token_hash, label, scope, created_at, revoked_at
`

type CreateTokenParams struct {
	TokenHash string     `json:"token_hash"`
	Label     string     `json:"label"`
	Scope     TokenScope `json:"scope"`
}

func (q *Queries) CreateToken(ctx context.Context, arg CreateTokenParams) (Token, error) {
	row := q.db.QueryRow(ctx, createToken, arg.TokenHash, arg.Label, arg.Scope)
	var i Token
	err := row.Scan(
		&i.ID,
		&i.TokenHash,
		&i.Label,
		&i.Scope,
		&i.CreatedAt,
		&i.RevokedAt,
	)
	return i, err
}

const getTokenByHash = `-- name: GetTokenByHash :one
select id, token_hash, label, scope, created_at, revoked_at from tokens
where token_hash = $1 and revoked_at is null
`

func (q *Queries) GetTokenByHash(ctx context.Context, tokenHash string) (Token, error) {
	row := q.db.QueryRow(ctx, getTokenByHash, tokenHash)
	var i Token
	err := row.Scan(
		&i.ID,
		&i.TokenHash,
		&i.Label,
		&i.Scope,
		&i.CreatedAt,
		&i.RevokedAt,
	)
	return i, err
}

const revokeToken = `-- name: RevokeToken :exec
update tokens
set revoked_at = now()
where id = $1
`

func (q *Queries) RevokeToken(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, revokeToken, id)
	return err
}
