// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: training.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const archiveWorkoutTemplate = `-- name: ArchiveWorkoutTemplate :one
update workout_templates
set archived = true
where id = $1 and is_default = false
returning id, name, workout_type, is_default, archived, created_at
`

func (q *Queries) ArchiveWorkoutTemplate(ctx context.Context, id pgtype.UUID) (WorkoutTemplate, error) {
	row := q.db.QueryRow(ctx, archiveWorkoutTemplate, id)
	var i WorkoutTemplate
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.WorkoutType,
		&i.IsDefault,
		&i.Archived,
		&i.CreatedAt,
	)
	return i, err
}

const clearDefaultWorkoutTemplate = `-- name: ClearDefaultWorkoutTemplate :exec
update workout_templates
set is_default = false
where workout_type = $1 and is_default = true
`

func (q *Queries) ClearDefaultWorkoutTemplate(ctx context.Context, workoutType string) error {
	_, err := q.db.Exec(ctx, clearDefaultWorkoutTemplate, workoutType)
	return err
}

const createExercise = `-- name: CreateExercise :one
insert into exercises (name, type, workout_type)
values ($1, $2, $3)
returning id, name, type, workout_type, created_at
`

type CreateExerciseParams struct {
	Name        string `json:"name"`
	Type        string `json:"type"`
	WorkoutType string `json:"workout_type"`
}

func (q *Queries) CreateExercise(ctx context.Context, arg CreateExerciseParams) (Exercise, error) {
	row := q.db.QueryRow(ctx, createExercise, arg.Name, arg.Type, arg.WorkoutType)
	var i Exercise
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.WorkoutType,
		&i.CreatedAt,
	)
	return i, err
}

const createWorkoutSession = `-- name: CreateWorkoutSession :one
insert into workout_sessions (workout_type, template_id, date)
values ($1, $2, $3)
returning id, workout_type, template_id, note, date, finished_at, created_at
`

type CreateWorkoutSessionParams struct {
	WorkoutType string      `json:"workout_type"`
	TemplateID  pgtype.UUID `json:"template_id"`
	Date        pgtype.Date `json:"date"`
}

func (q *Queries) CreateWorkoutSession(ctx context.Context, arg CreateWorkoutSessionParams) (WorkoutSession, error) {
	row := q.db.QueryRow(ctx, createWorkoutSession, arg.WorkoutType, arg.TemplateID, arg.Date)
	var i WorkoutSession
	err := row.Scan(
		&i.ID,
		&i.WorkoutType,
		&i.TemplateID,
		&i.Note,
		&i.Date,
		&i.FinishedAt,
		&i.CreatedAt,
	)
	return i, err
}

const createWorkoutSessionExercise = `-- name: CreateWorkoutSessionExercise :one
insert into workout_session_exercises (session_id, exercise_id, exercise_name, position)
values (
  $1, $2, $3,
  (select coalesce(max(position), -1) + 1 from workout_session_exercises where session_id = $1)
)
returning id, session_id, exercise_id, exercise_name, note, position, created_at
`

type CreateWorkoutSessionExerciseParams struct {
	SessionID    pgtype.UUID `json:"session_id"`
	ExerciseID   pgtype.UUID `json:"exercise_id"`
	ExerciseName string      `json:"exercise_name"`
}

func (q *Queries) CreateWorkoutSessionExercise(ctx context.Context, arg CreateWorkoutSessionExerciseParams) (WorkoutSessionExercise, error) {
	row := q.db.QueryRow(ctx, createWorkoutSessionExercise, arg.SessionID, arg.ExerciseID, arg.ExerciseName)
	var i WorkoutSessionExercise
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.ExerciseID,
		&i.ExerciseName,
		&i.Note,
		&i.Position,
		&i.CreatedAt,
	)
	return i, err
}

const createWorkoutSet = `-- name: CreateWorkoutSet :one
insert into workout_sets (
  session_exercise_id, set_type, weight_kg, reps, duration_sec, distance_m, note
)
values ($1, $2, $3, $4, $5, $6, $7)
returning id, session_exercise_id, set_type, confirmed, note, weight_kg, reps, duration_sec, distance_m, created_at
`

type CreateWorkoutSetParams struct {
	SessionExerciseID pgtype.UUID    `json:"session_exercise_id"`
	SetType           string         `json:"set_type"`
	WeightKg          pgtype.Numeric `json:"weight_kg"`
	Reps              pgtype.Int4    `json:"reps"`
	DurationSec       pgtype.Int4    `json:"duration_sec"`
	DistanceM         pgtype.Numeric `json:"distance_m"`
	Note              pgtype.Text    `json:"note"`
}

func (q *Queries) CreateWorkoutSet(ctx context.Context, arg CreateWorkoutSetParams) (WorkoutSet, error) {
	row := q.db.QueryRow(ctx, createWorkoutSet,
		arg.SessionExerciseID,
		arg.SetType,
		arg.WeightKg,
		arg.Reps,
		arg.DurationSec,
		arg.DistanceM,
		arg.Note,
	)
	var i WorkoutSet
	err := row.Scan(
		&i.ID,
		&i.SessionExerciseID,
		&i.SetType,
		&i.Confirmed,
		&i.Note,
		&i.WeightKg,
		&i.Reps,
		&i.DurationSec,
		&i.DistanceM,
		&i.CreatedAt,
	)
	return i, err
}

const createWorkoutTemplate = `-- name: CreateWorkoutTemplate :one
insert into workout_templates (name, workout_type)
values ($1, $2)
returning id, name, workout_type, is_default, archived, created_at
`

type CreateWorkoutTemplateParams struct {
	Name        string `json:"name"`
	WorkoutType string `json:"workout_type"`
}

func (q *Queries) CreateWorkoutTemplate(ctx context.Context, arg CreateWorkoutTemplateParams) (WorkoutTemplate, error) {
	row := q.db.QueryRow(ctx, createWorkoutTemplate, arg.Name, arg.WorkoutType)
	var i WorkoutTemplate
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.WorkoutType,
		&i.IsDefault,
		&i.Archived,
		&i.CreatedAt,
	)
	return i, err
}

const createWorkoutTemplateSet = `-- name: CreateWorkoutTemplateSet :one
insert into workout_template_sets (
  template_id, exercise_id, exercise_name, position, set_type, weight_kg, reps, duration_sec, distance_m
)
values ($1, $2, $3, $4, $5, $6, $7, $8, $9)
returning id, template_id, exercise_id, exercise_name, position, set_type, weight_kg, reps, duration_sec, distance_m, created_at
`

type CreateWorkoutTemplateSetParams struct {
	TemplateID   pgtype.UUID    `json:"template_id"`
	ExerciseID   pgtype.UUID    `json:"exercise_id"`
	ExerciseName string         `json:"exercise_name"`
	Position     int32          `json:"position"`
	SetType      string         `json:"set_type"`
	WeightKg     pgtype.Numeric `json:"weight_kg"`
	Reps         pgtype.Int4    `json:"reps"`
	DurationSec  pgtype.Int4    `json:"duration_sec"`
	DistanceM    pgtype.Numeric `json:"distance_m"`
}

func (q *Queries) CreateWorkoutTemplateSet(ctx context.Context, arg CreateWorkoutTemplateSetParams) (WorkoutTemplateSet, error) {
	row := q.db.QueryRow(ctx, createWorkoutTemplateSet,
		arg.TemplateID,
		arg.ExerciseID,
		arg.ExerciseName,
		arg.Position,
		arg.SetType,
		arg.WeightKg,
		arg.Reps,
		arg.DurationSec,
		arg.DistanceM,
	)
	var i WorkoutTemplateSet
	err := row.Scan(
		&i.ID,
		&i.TemplateID,
		&i.ExerciseID,
		&i.ExerciseName,
		&i.Position,
		&i.SetType,
		&i.WeightKg,
		&i.Reps,
		&i.DurationSec,
		&i.DistanceM,
		&i.CreatedAt,
	)
	return i, err
}

const deleteExercise = `-- name: DeleteExercise :exec
delete from exercises
where id = $1
`

func (q *Queries) DeleteExercise(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteExercise, id)
	return err
}

const deleteWorkoutSession = `-- name: DeleteWorkoutSession :exec
delete from workout_sessions
where id = $1
`

func (q *Queries) DeleteWorkoutSession(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteWorkoutSession, id)
	return err
}

const deleteWorkoutSessionExercise = `-- name: DeleteWorkoutSessionExercise :exec
delete from workout_session_exercises
where id = $1
`

func (q *Queries) DeleteWorkoutSessionExercise(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteWorkoutSessionExercise, id)
	return err
}

const deleteWorkoutSet = `-- name: DeleteWorkoutSet :exec
delete from workout_sets
where id = $1
`

func (q *Queries) DeleteWorkoutSet(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteWorkoutSet, id)
	return err
}

const deleteWorkoutSetsBySessionExercise = `-- name: DeleteWorkoutSetsBySessionExercise :exec
delete from workout_sets
where session_exercise_id = $1
`

func (q *Queries) DeleteWorkoutSetsBySessionExercise(ctx context.Context, sessionExerciseID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteWorkoutSetsBySessionExercise, sessionExerciseID)
	return err
}

const deleteWorkoutTemplateSetsByTemplate = `-- name: DeleteWorkoutTemplateSetsByTemplate :exec
delete from workout_template_sets
where template_id = $1
`

func (q *Queries) DeleteWorkoutTemplateSetsByTemplate(ctx context.Context, templateID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteWorkoutTemplateSetsByTemplate, templateID)
	return err
}

const finishWorkoutSession = `-- name: FinishWorkoutSession :one
update workout_sessions
set finished_at = now()
where id = $1
returning id, workout_type, template_id, note, date, finished_at, created_at
`

func (q *Queries) FinishWorkoutSession(ctx context.Context, id pgtype.UUID) (WorkoutSession, error) {
	row := q.db.QueryRow(ctx, finishWorkoutSession, id)
	var i WorkoutSession
	err := row.Scan(
		&i.ID,
		&i.WorkoutType,
		&i.TemplateID,
		&i.Note,
		&i.Date,
		&i.FinishedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getExercise = `-- name: GetExercise :one
select id, name, type, workout_type, created_at from exercises
where id = $1
`

func (q *Queries) GetExercise(ctx context.Context, id pgtype.UUID) (Exercise, error) {
	row := q.db.QueryRow(ctx, getExercise, id)
	var i Exercise
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.WorkoutType,
		&i.CreatedAt,
	)
	return i, err
}

const getLastSessionExerciseForType = `-- name: GetLastSessionExerciseForType :one
select workout_session_exercises.id, workout_session_exercises.session_id, workout_session_exercises.exercise_id, workout_session_exercises.exercise_name, workout_session_exercises.note, workout_session_exercises.position, workout_session_exercises.created_at
from workout_session_exercises
join workout_sessions on workout_sessions.id = workout_session_exercises.session_id
where workout_session_exercises.exercise_id = $1
  and workout_sessions.workout_type = $2
  and workout_sessions.finished_at is not null
order by workout_sessions.date desc, workout_sessions.created_at desc
limit 1
`

type GetLastSessionExerciseForTypeParams struct {
	ExerciseID  pgtype.UUID `json:"exercise_id"`
	WorkoutType string      `json:"workout_type"`
}

// Progressive overload: the last Session-Exercise for this Exercise, from
// the last Session of the given Workout Type — a two-step lookup (this,
// then ListWorkoutSetsBySessionExercise for its sets) rather than one
// complex join, matching how the rest of this codebase composes simple
// queries in the handler instead of building the joined result in SQL.
func (q *Queries) GetLastSessionExerciseForType(ctx context.Context, arg GetLastSessionExerciseForTypeParams) (WorkoutSessionExercise, error) {
	row := q.db.QueryRow(ctx, getLastSessionExerciseForType, arg.ExerciseID, arg.WorkoutType)
	var i WorkoutSessionExercise
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.ExerciseID,
		&i.ExerciseName,
		&i.Note,
		&i.Position,
		&i.CreatedAt,
	)
	return i, err
}

const getUnfinishedWorkoutSession = `-- name: GetUnfinishedWorkoutSession :one
select id, workout_type, template_id, note, date, finished_at, created_at from workout_sessions
where finished_at is null
order by created_at desc
limit 1
`

func (q *Queries) GetUnfinishedWorkoutSession(ctx context.Context) (WorkoutSession, error) {
	row := q.db.QueryRow(ctx, getUnfinishedWorkoutSession)
	var i WorkoutSession
	err := row.Scan(
		&i.ID,
		&i.WorkoutType,
		&i.TemplateID,
		&i.Note,
		&i.Date,
		&i.FinishedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getWorkoutSession = `-- name: GetWorkoutSession :one
select id, workout_type, template_id, note, date, finished_at, created_at from workout_sessions
where id = $1
`

func (q *Queries) GetWorkoutSession(ctx context.Context, id pgtype.UUID) (WorkoutSession, error) {
	row := q.db.QueryRow(ctx, getWorkoutSession, id)
	var i WorkoutSession
	err := row.Scan(
		&i.ID,
		&i.WorkoutType,
		&i.TemplateID,
		&i.Note,
		&i.Date,
		&i.FinishedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getWorkoutTemplate = `-- name: GetWorkoutTemplate :one
select id, name, workout_type, is_default, archived, created_at from workout_templates
where id = $1
`

func (q *Queries) GetWorkoutTemplate(ctx context.Context, id pgtype.UUID) (WorkoutTemplate, error) {
	row := q.db.QueryRow(ctx, getWorkoutTemplate, id)
	var i WorkoutTemplate
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.WorkoutType,
		&i.IsDefault,
		&i.Archived,
		&i.CreatedAt,
	)
	return i, err
}

const listExercises = `-- name: ListExercises :many
select id, name, type, workout_type, created_at from exercises
order by name asc
`

func (q *Queries) ListExercises(ctx context.Context) ([]Exercise, error) {
	rows, err := q.db.Query(ctx, listExercises)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Exercise
	for rows.Next() {
		var i Exercise
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Type,
			&i.WorkoutType,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkoutSessionExercises = `-- name: ListWorkoutSessionExercises :many
select id, session_id, exercise_id, exercise_name, note, position, created_at from workout_session_exercises
where session_id = $1
order by position asc
`

func (q *Queries) ListWorkoutSessionExercises(ctx context.Context, sessionID pgtype.UUID) ([]WorkoutSessionExercise, error) {
	rows, err := q.db.Query(ctx, listWorkoutSessionExercises, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WorkoutSessionExercise
	for rows.Next() {
		var i WorkoutSessionExercise
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.ExerciseID,
			&i.ExerciseName,
			&i.Note,
			&i.Position,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkoutSessions = `-- name: ListWorkoutSessions :many
select id, workout_type, template_id, note, date, finished_at, created_at from workout_sessions
order by date desc, created_at desc
`

func (q *Queries) ListWorkoutSessions(ctx context.Context) ([]WorkoutSession, error) {
	rows, err := q.db.Query(ctx, listWorkoutSessions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WorkoutSession
	for rows.Next() {
		var i WorkoutSession
		if err := rows.Scan(
			&i.ID,
			&i.WorkoutType,
			&i.TemplateID,
			&i.Note,
			&i.Date,
			&i.FinishedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkoutSetsBySession = `-- name: ListWorkoutSetsBySession :many
select workout_sets.id, workout_sets.session_exercise_id, workout_sets.set_type, workout_sets.confirmed, workout_sets.note, workout_sets.weight_kg, workout_sets.reps, workout_sets.duration_sec, workout_sets.distance_m, workout_sets.created_at
from workout_sets
join workout_session_exercises on workout_session_exercises.id = workout_sets.session_exercise_id
where workout_session_exercises.session_id = $1
order by workout_sets.created_at asc
`

func (q *Queries) ListWorkoutSetsBySession(ctx context.Context, sessionID pgtype.UUID) ([]WorkoutSet, error) {
	rows, err := q.db.Query(ctx, listWorkoutSetsBySession, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WorkoutSet
	for rows.Next() {
		var i WorkoutSet
		if err := rows.Scan(
			&i.ID,
			&i.SessionExerciseID,
			&i.SetType,
			&i.Confirmed,
			&i.Note,
			&i.WeightKg,
			&i.Reps,
			&i.DurationSec,
			&i.DistanceM,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkoutSetsBySessionExercise = `-- name: ListWorkoutSetsBySessionExercise :many
select id, session_exercise_id, set_type, confirmed, note, weight_kg, reps, duration_sec, distance_m, created_at from workout_sets
where session_exercise_id = $1
order by created_at asc
`

func (q *Queries) ListWorkoutSetsBySessionExercise(ctx context.Context, sessionExerciseID pgtype.UUID) ([]WorkoutSet, error) {
	rows, err := q.db.Query(ctx, listWorkoutSetsBySessionExercise, sessionExerciseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WorkoutSet
	for rows.Next() {
		var i WorkoutSet
		if err := rows.Scan(
			&i.ID,
			&i.SessionExerciseID,
			&i.SetType,
			&i.Confirmed,
			&i.Note,
			&i.WeightKg,
			&i.Reps,
			&i.DurationSec,
			&i.DistanceM,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkoutTemplateSets = `-- name: ListWorkoutTemplateSets :many
select id, template_id, exercise_id, exercise_name, position, set_type, weight_kg, reps, duration_sec, distance_m, created_at from workout_template_sets
where template_id = $1
order by position asc
`

func (q *Queries) ListWorkoutTemplateSets(ctx context.Context, templateID pgtype.UUID) ([]WorkoutTemplateSet, error) {
	rows, err := q.db.Query(ctx, listWorkoutTemplateSets, templateID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WorkoutTemplateSet
	for rows.Next() {
		var i WorkoutTemplateSet
		if err := rows.Scan(
			&i.ID,
			&i.TemplateID,
			&i.ExerciseID,
			&i.ExerciseName,
			&i.Position,
			&i.SetType,
			&i.WeightKg,
			&i.Reps,
			&i.DurationSec,
			&i.DistanceM,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkoutTemplates = `-- name: ListWorkoutTemplates :many
select id, name, workout_type, is_default, archived, created_at from workout_templates
order by workout_type asc, is_default desc, name asc
`

func (q *Queries) ListWorkoutTemplates(ctx context.Context) ([]WorkoutTemplate, error) {
	rows, err := q.db.Query(ctx, listWorkoutTemplates)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WorkoutTemplate
	for rows.Next() {
		var i WorkoutTemplate
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.WorkoutType,
			&i.IsDefault,
			&i.Archived,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reorderWorkoutSessionExercises = `-- name: ReorderWorkoutSessionExercises :exec
update workout_session_exercises
set position = t.idx - 1
from unnest($1::uuid[]) with ordinality as t(id, idx)
where workout_session_exercises.id = t.id
`

func (q *Queries) ReorderWorkoutSessionExercises(ctx context.Context, ids []pgtype.UUID) error {
	_, err := q.db.Exec(ctx, reorderWorkoutSessionExercises, ids)
	return err
}

const replaceWorkoutSessionExerciseExercise = `-- name: ReplaceWorkoutSessionExerciseExercise :one
update workout_session_exercises
set exercise_id = $2, exercise_name = $3, note = null
where id = $1
returning id, session_id, exercise_id, exercise_name, note, position, created_at
`

type ReplaceWorkoutSessionExerciseExerciseParams struct {
	ID           pgtype.UUID `json:"id"`
	ExerciseID   pgtype.UUID `json:"exercise_id"`
	ExerciseName string      `json:"exercise_name"`
}

func (q *Queries) ReplaceWorkoutSessionExerciseExercise(ctx context.Context, arg ReplaceWorkoutSessionExerciseExerciseParams) (WorkoutSessionExercise, error) {
	row := q.db.QueryRow(ctx, replaceWorkoutSessionExerciseExercise, arg.ID, arg.ExerciseID, arg.ExerciseName)
	var i WorkoutSessionExercise
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.ExerciseID,
		&i.ExerciseName,
		&i.Note,
		&i.Position,
		&i.CreatedAt,
	)
	return i, err
}

const restoreWorkoutTemplate = `-- name: RestoreWorkoutTemplate :one
update workout_templates
set archived = false
where id = $1
returning id, name, workout_type, is_default, archived, created_at
`

func (q *Queries) RestoreWorkoutTemplate(ctx context.Context, id pgtype.UUID) (WorkoutTemplate, error) {
	row := q.db.QueryRow(ctx, restoreWorkoutTemplate, id)
	var i WorkoutTemplate
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.WorkoutType,
		&i.IsDefault,
		&i.Archived,
		&i.CreatedAt,
	)
	return i, err
}

const setDefaultWorkoutTemplate = `-- name: SetDefaultWorkoutTemplate :one
update workout_templates
set is_default = true, archived = false
where id = $1
returning id, name, workout_type, is_default, archived, created_at
`

func (q *Queries) SetDefaultWorkoutTemplate(ctx context.Context, id pgtype.UUID) (WorkoutTemplate, error) {
	row := q.db.QueryRow(ctx, setDefaultWorkoutTemplate, id)
	var i WorkoutTemplate
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.WorkoutType,
		&i.IsDefault,
		&i.Archived,
		&i.CreatedAt,
	)
	return i, err
}

const updateWorkoutSession = `-- name: UpdateWorkoutSession :one
update workout_sessions
set
  note = coalesce($2, note),
  created_at = coalesce($3, created_at),
  finished_at = coalesce($4, finished_at)
where id = $1
returning id, workout_type, template_id, note, date, finished_at, created_at
`

type UpdateWorkoutSessionParams struct {
	ID         pgtype.UUID        `json:"id"`
	Note       pgtype.Text        `json:"note"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	FinishedAt pgtype.Timestamptz `json:"finished_at"`
}

func (q *Queries) UpdateWorkoutSession(ctx context.Context, arg UpdateWorkoutSessionParams) (WorkoutSession, error) {
	row := q.db.QueryRow(ctx, updateWorkoutSession,
		arg.ID,
		arg.Note,
		arg.CreatedAt,
		arg.FinishedAt,
	)
	var i WorkoutSession
	err := row.Scan(
		&i.ID,
		&i.WorkoutType,
		&i.TemplateID,
		&i.Note,
		&i.Date,
		&i.FinishedAt,
		&i.CreatedAt,
	)
	return i, err
}

const updateWorkoutSessionExercise = `-- name: UpdateWorkoutSessionExercise :one
update workout_session_exercises
set note = coalesce($2, note)
where id = $1
returning id, session_id, exercise_id, exercise_name, note, position, created_at
`

type UpdateWorkoutSessionExerciseParams struct {
	ID   pgtype.UUID `json:"id"`
	Note pgtype.Text `json:"note"`
}

func (q *Queries) UpdateWorkoutSessionExercise(ctx context.Context, arg UpdateWorkoutSessionExerciseParams) (WorkoutSessionExercise, error) {
	row := q.db.QueryRow(ctx, updateWorkoutSessionExercise, arg.ID, arg.Note)
	var i WorkoutSessionExercise
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.ExerciseID,
		&i.ExerciseName,
		&i.Note,
		&i.Position,
		&i.CreatedAt,
	)
	return i, err
}

const updateWorkoutSet = `-- name: UpdateWorkoutSet :one
update workout_sets
set
  set_type = coalesce($2, set_type),
  confirmed = coalesce($3, confirmed),
  weight_kg = coalesce($4, weight_kg),
  reps = coalesce($5, reps),
  duration_sec = coalesce($6, duration_sec),
  distance_m = coalesce($7, distance_m),
  note = coalesce($8, note)
where id = $1
returning id, session_exercise_id, set_type, confirmed, note, weight_kg, reps, duration_sec, distance_m, created_at
`

type UpdateWorkoutSetParams struct {
	ID          pgtype.UUID    `json:"id"`
	SetType     pgtype.Text    `json:"set_type"`
	Confirmed   pgtype.Bool    `json:"confirmed"`
	WeightKg    pgtype.Numeric `json:"weight_kg"`
	Reps        pgtype.Int4    `json:"reps"`
	DurationSec pgtype.Int4    `json:"duration_sec"`
	DistanceM   pgtype.Numeric `json:"distance_m"`
	Note        pgtype.Text    `json:"note"`
}

func (q *Queries) UpdateWorkoutSet(ctx context.Context, arg UpdateWorkoutSetParams) (WorkoutSet, error) {
	row := q.db.QueryRow(ctx, updateWorkoutSet,
		arg.ID,
		arg.SetType,
		arg.Confirmed,
		arg.WeightKg,
		arg.Reps,
		arg.DurationSec,
		arg.DistanceM,
		arg.Note,
	)
	var i WorkoutSet
	err := row.Scan(
		&i.ID,
		&i.SessionExerciseID,
		&i.SetType,
		&i.Confirmed,
		&i.Note,
		&i.WeightKg,
		&i.Reps,
		&i.DurationSec,
		&i.DistanceM,
		&i.CreatedAt,
	)
	return i, err
}
